version: 2

jobs:
  build:
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: yarn
      - run:
          name: "Run tests"
          command: yarn test-ci
